services:
  db:
    image: mysql:8.0.31
    volumes:
      - mysql-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD  #=== .envの環境変数から持ってくる
    ports:
      - '3306:3306'
  
  backend:
    build: 
      context: ./backend
    volumes:
      - ./backend:/$WORKDIR
      - gem-store:/usr/local/bundle
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  mysql-store:
  gem-store: