services:
  db:
    image: mysql:8.0.31
    volumes:
      - mysql-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
  
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    depends_on:
      - db
volumes:
  mysql-store: