services:
  db:
    image: mysql:8.0.31
  backend:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db