services:
  db:
    image: mysql:8.0.31
  backend:
    build: .
    command: 
      "bash -c 'rm -f tmp/pids/server.pid &&
      bundle &&
      bin/rails db:create db:migrate db:seed &&
      bundle exec rails server -b 0.0.0.0'"
    volumes:
      - .:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db