services:
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_volume:/var/lib/mysql
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: 
      "bash -c 'rm -f tmp/pids/server.pid &&
      bundle &&
      bin/rails db:create db:migrate db:seed &&
      bundle exec rails server -b 0.0.0.0'"
    volumes:
      - .:/backend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
volumes:
  mysql_volume:
